// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gisefsuikkfzzepzkkzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdpc2Vmc3Vpa2tmenplcHpra3pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3Mzk3NDQsImV4cCI6MjA1NjMxNTc0NH0.xl2AN1nbo_y4_gBkyVxBj4Za8ZjLtKhetD6p65Qs5-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);